version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: jitendrapalei/notes-db
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/msql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass  


  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01: 
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEAFULT_USER=guest
      - RABBITMQ_DEAFULT_PASS=guest 
      
    
  vproapp:
    build: 
      context: ./Docker-files/app
    image: jitendrapalei/notes-app
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vprodbdata:/usr/local/tomcat/webapps
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass  

      
  vproweb:
    build: 
      context: ./Docker-files/web
    image: jitendrapalei/notes-web
    container_name: vproweb
    ports:
      - "80:80"
      
volumes:
  vprodbdata:
  vproappdata: 